### ISSUE TITLE
Floating point underflow on FreeBSD

### ISSUE THREAD

**Issue by Martinfx** [Swartz27/xray-16#1223]
**Describe the bug**

Thread 1 "Primary thread" received signal SIGFPE, Arithmetic exception.
Floating point underflow.

**To Reproduce**
Compile with clang on FreeBSD 13.1
run ./bin/x64/Debug/xr_3da

**BugTrap error report**
```
scalbnf () at /usr/src/lib/msun/amd64/s_scalbnf.S:33
33		fildl	-4(%rsp)
(gdb) bt
#0  scalbnf () at /usr/src/lib/msun/amd64/s_scalbnf.S:33
#1  0x000000080081c4c8 in powf (x=<optimized out>, y=<optimized out>) at /usr/src/lib/msun/src/e_powf.c:249
#2  0x0000000807512b24 in CRenderTarget::build_textures (this=0x807a7fa00) at gl_rendertarget_build_textures.cpp:80
#3  0x0000000807674498 in CRenderTarget::CRenderTarget (this=0x807a7fa00) at /media/ST3000DM007-1WY10G_ZTT0SM4Q_p1/code/xray-16/src/Layers/xrRender_R2/r2_rendertarget.cpp:770
#4  0x000000080765fa76 in xr_new<CRenderTarget> () at /media/ST3000DM007-1WY10G_ZTT0SM4Q_p1/code/xray-16/src/xrCore/xrMemory.h:121
#5  CRender::create (this=0x807747500 <RImplementation>) at /media/ST3000DM007-1WY10G_ZTT0SM4Q_p1/code/xray-16/src/Layers/xrRender_R2/r2.cpp:613
#6  0x000000080758293d in D3DXRenderBase::OnDeviceCreate (this=0x807747500 <RImplementation>, shName=<optimized out>) at /media/ST3000DM007-1WY10G_ZTT0SM4Q_p1/code/xray-16/src/Layers/xrRender/D3DXRenderBase.cpp:118
#7  0x0000000800349f7c in CRenderDevice::CreateInternal (this=0x80037abb0 <Device>) at Device_create.cpp:62
#8  0x0000000800349d78 in CRenderDevice::Create (this=0xffffff7d) at Device_create.cpp:29
#9  0x000000080033a550 in Startup () at main.cpp:299
#10 0x000000080033adb5 in RunApplication () at main.cpp:366
#11 0x0000000000202640 in entry_point (commandLine=commandLine@entry=0x801608038 "") at entry_point.cpp:96
#12 0x000000000020271b in main (argc=<optimized out>, argv=<optimized out>) at entry_point.cpp:155
(gdb) exit
```

**Desktop (please complete the following information):**
FreeBSD 13.1 AMD64
! Couldn't create surface from image: Parameter 'src' is invalid
OpenXRay Mixed build 8741, Jan 12 2023 (BSD 64-bit, shared)
Custom build from commit[6c499cadce2f3fa5c4d8fdc41ba8f00e9237ec9a] branch[dev]
 

**Additional context**

**Comment by dasehak** [comment]
Try to use this: https://github.com/OpenXRay/xray-16/pull/1153/commits/323872242fe3d2e51872ec1e263337338ad5330d

**Comment by Martinfx** [comment]
It works. This commit isnt in git

**Comment by Xottab-DUTY** [comment]
> It works. This commit isnt in git

@Martinfx, I just merged the commit! :)
