### ISSUE TITLE
[COP] - FATAL ERROR in SkeletonRigid.cpp with the description "anim kils bone matrix"

### ISSUE THREAD

**Issue by BielBdeLuna** [Swartz27/xray-16#972]
**Describe the bug**
random crash due to Fatal Error with the following description `anim kils bone matrix`

**To Reproduce**
random crash

**Screenshots**
none.

**BugTrap error report**
the bug trap file is too long due to the engine being compiled with `-DMASTER_GOLD OFF` so here is the error part in the end:

<details>
  <summary>Click here to expand/collapse.</summary>
  <p>
  
ODE Message 2: vector has zero size in dNormalize4()

ODE Message 2: vector has zero size in dNormalize4()

ODE Message 2: vector has zero size in dNormalize4()

ODE Message 2: vector has zero size in dNormalize4()

ODE Message 2: vector has zero size in dNormalize4()

ODE Message 2: vector has zero size in dNormalize4()

ODE Message 2: vector has zero size in dNormalize4()

ODE Message 2: vector has zero size in dNormalize4()

ODE Message 2: vector has zero size in dNormalize4()

ODE Message 2: vector has zero size in dNormalize4()

ODE Message 2: vector has zero size in dNormalize4()

ODE Message 2: vector has zero size in dNormalize4()

ODE Message 2: vector has zero size in dNormalize4()

ODE Message 2: vector has zero size in dNormalize4()

ODE Message 2: vector has zero size in dNormalize4()

ODE Message 2: vector has zero size in dNormalize4()

ODE Message 2: vector has zero size in dNormalize4()

ODE Message 2: vector has zero size in dNormalize4()

ODE Message 2: vector has zero size in dNormalize4()

ODE Message 2: vector has zero size in dNormalize4()

ODE Message 2: vector has zero size in dNormalize4()

ODE Message 2: vector has zero size in dNormalize4()

ODE Message 2: vector has zero size in dNormalize4()
 
FATAL ERROR
 
[error] Expression    : _valid(bi.mTransform)
[error] Function      : CLBone
[error] File          : /home/biel/code/xray-16/src/Layers/xrRender/SkeletonRigid.cpp
[error] Line          : 211
[error] Description   : anim kils bone matrix
 

stack trace:

xrDebug::GatherInfo(char*, unsigned long, ErrorLocation const&, char const*, char const*, char const*, char const*)
xrDebug::Fail(bool&, ErrorLocation const&, char const*, char const*, char const*, char const*)
/lib/x86_64-linux-gnu/xrRender_GL.so(+0x147d22) [0x7fa10a565d22]
/lib/x86_64-linux-gnu/xrRender_GL.so(+0x147db8) [0x7fa10a565db8]
/lib/x86_64-linux-gnu/xrRender_GL.so(+0x147de4) [0x7fa10a565de4]
/lib/x86_64-linux-gnu/xrRender_GL.so(+0x147de4) [0x7fa10a565de4]
/lib/x86_64-linux-gnu/xrRender_GL.so(+0x1488b0) [0x7fa10a5668b0]
/lib/x86_64-linux-gnu/xrRender_GL.so(+0x10a795) [0x7fa10a528795]
/lib/x86_64-linux-gnu/xrGame.so(+0xd9f09c) [0x7fa10854609c]
/lib/x86_64-linux-gnu/xrGame.so(+0x153a68f) [0x7fa108ce168f]
/lib/x86_64-linux-gnu/xrRender_GL.so(+0x17e8fb) [0x7fa10a59c8fb]
/lib/x86_64-linux-gnu/xrRender_GL.so(+0x17f003) [0x7fa10a59d003]
/lib/x86_64-linux-gnu/xrGame.so(+0xeac679) [0x7fa108653679]
CRenderDevice::DoRender()
CRenderDevice::ProcessFrame()
/lib/x86_64-linux-gnu/xrEngine.so(+0x43e2b) [0x7fa12006be2b]
CRenderDevice::Run()
Startup()
RunApplication()
xr_3da(+0x1885) [0x55e88fbed885]
Trampa de traçat/punt d’aturada (s'ha bolcat la memòria)

  </p>
</details>

**Desktop (please complete the following information):**
 - OS: [Ubuntu 21.10]
 - OpenXRay build version [ff7b9d2f152b4e06f3cd0dd943f30f8f60f43e1f] but compiled with -DMASTER_GOLD OFF

**Comment by jjdredd** [comment]
I got the same error and was wondering how did you manage to test with master_gold off in https://github.com/OpenXRay/xray-16/issues/931

**Comment by BielBdeLuna** [comment]
what do you mean?

**Comment by jjdredd** [comment]
How did you manage to test with master gold off in #931 when your game crashes with master gold off according to this issue?

**Comment by BielBdeLuna** [comment]
Because the crashes are apparently at random times, meaning that happen during gameplay and apparently unrelated to whatever the player is doing.

**Comment by jjdredd** [comment]
Strange, I get this crash all the time.

**Comment by BielBdeLuna** [comment]
I get this error whenever I load a specific save, in the kindergarden in prypiat:

here is the backtrace:

<details>
<summary>Click here to expand/collapse.</summary>
<p>
(...)

ODE Message 2: vector has zero size in dNormalize4()

ODE Message 2: vector has zero size in dNormalize4()

ODE Message 2: vector has zero size in dNormalize4()

ODE Message 2: vector has zero size in dNormalize4()

ODE Message 2: vector has zero size in dNormalize4()
* Loading script: ph_on_hit.script
* Loading script: ph_door.script
* Loading script: sr_idle.script
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@nil'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@nil'
* Loading script: sim_squad_actions.script
[LUA]  ...ll of Pripyat\sim_squad_scripted:(476):set_location_types for squad [simulation_bloodsucker19742]
[LUA]  ...ll of Pripyat\sim_squad_scripted:(476):set_location_types for squad [simulation_bloodsucker19742]
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@destroy_garry'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@nil'
[LUA]  ...ll of Pripyat\sim_squad_scripted:(476):set_location_types for squad [zombied_sim_squad_advanced11812]
[LUA]  ...ll of Pripyat\sim_squad_scripted:(476):set_location_types for squad [zombied_sim_squad_advanced11812]
* Loading script: news_manager.script
[LUA]  ...ll of Pripyat\sim_squad_scripted:(476):set_location_types for squad [zombied_sim_squad_advanced13240]
[LUA]  ...ll of Pripyat\sim_squad_scripted:(476):set_location_types for squad [zombied_sim_squad_advanced13240]
[LUA]  UPDATE INVULNERABILITY. npc[pri_a25_base_medic9106] = [true]
[LUA]  ...ll of Pripyat\sim_squad_scripted:(476):set_location_types for squad [pri_a25_base_army_medic9105]
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@end'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@pri_b303_toolkit_3'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@wait_for_start'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@after'
* Loading script: ph_death.script
[LUA]  ....E.R. - Call of Pripyat\ph_death:(30):DEBUG: add_to_binder: npc:name()='pri_a25_antenna_destroyable_barrier', scheme='ph_on_death', section='ph_on_death'
* Loading script: ph_idle.script
[LUA]  ...K.E.R. - Call of Pripyat\ph_idle:(58):DEBUG: add_to_binder: scheme='ph_idle', section='ph_idle'
[LUA]  ...K.E.R. - Call of Pripyat\ph_idle:(13):_hr: action_idle:reset_scheme: self.object:name()='pri_a25_hospital_fense_blocker_1'
[LUA]  ...K.E.R. - Call of Pripyat\ph_idle:(58):DEBUG: add_to_binder: scheme='ph_idle', section='ph_idle'
[LUA]  ...K.E.R. - Call of Pripyat\ph_idle:(13):_hr: action_idle:reset_scheme: self.object:name()='pri_a25_hospital_fense_blocker_2'
[LUA]  ...K.E.R. - Call of Pripyat\ph_idle:(58):DEBUG: add_to_binder: scheme='ph_idle', section='ph_idle'
[LUA]  ...K.E.R. - Call of Pripyat\ph_idle:(13):_hr: action_idle:reset_scheme: self.object:name()='pripyat_physic_destroyable_object_0001'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@wait_for_start'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@wait'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@give_task'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@kindergarden_koval_snd'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@base_radio_snd_1'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@check_surge_end'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@start'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@start'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@wait'
* Loading script: heli_move.script
[LUA]  ...E.R. - Call of Pripyat\heli_move:(261):DEBUG: add_to_binder: npc:name()='pri_a28_heli_2', scheme='heli_move', section='heli_move@under_level'
* Loading script: heli_fly.script
* Loading script: heli_look.script
[LUA]  ...E.R. - Call of Pripyat\heli_move:(24):heli_move: reset_scheme: pri_a28_heli_2
[LUA]  ...E.R. - Call of Pripyat\heli_move:(261):DEBUG: add_to_binder: npc:name()='pri_a28_heli_1', scheme='heli_move', section='heli_move@under_level'
[LUA]  ...E.R. - Call of Pripyat\heli_move:(24):heli_move: reset_scheme: pri_a28_heli_1
[LUA]  ...K.E.R. - Call of Pripyat\ph_idle:(58):DEBUG: add_to_binder: scheme='ph_idle', section='ph_idle@wait'
[LUA]  ...K.E.R. - Call of Pripyat\ph_idle:(13):_hr: action_idle:reset_scheme: self.object:name()='pri_b303_screaming_dog'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@nil'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@nil'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@after'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@nil'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@wait_cam_3'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@wait'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@add_counter'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@spawn'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@start'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@nil'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@attack_timer'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@spawn'
* Loading script: sr_crow_spawner.script
[LUA]  ....E.R. - Call of Pripyat\sr_light:(15):Light zone insert
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@nil'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@nil'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@wait'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@nil'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@check_actor_antena_find'
* Loading script: sr_particle.script
[LUA]  ...R. - Call of Pripyat\sr_particle:(163):DEBUG: add_to_binder: scheme='sr_particle', section='sr_particle'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@kindergarten_polters_spawn'
[LUA]  ...- Call of Pripyat\sr_psy_antenna:(392):DEBUG: add_to_binder: scheme='sr_psy_antenna', section='sr_psy_antenna@check_antena_destroy'
[LUA]  ...K.E.R. - Call of Pripyat\ph_idle:(58):DEBUG: add_to_binder: scheme='ph_idle', section='ph_idle@open'
[LUA]  ...K.E.R. - Call of Pripyat\ph_idle:(13):_hr: action_idle:reset_scheme: self.object:name()='pri_b306_ph_button'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@talk_about_teleport'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@nil'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@nil'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@start'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@nil'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@nil'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@nil'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@end'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@end'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@nil'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@end'
[LUA]  ...K.E.R. - Call of Pripyat\ph_idle:(58):DEBUG: add_to_binder: scheme='ph_idle', section='ph_idle@wait'
[LUA]  ...K.E.R. - Call of Pripyat\ph_idle:(13):_hr: action_idle:reset_scheme: self.object:name()='pri_a16_ph_rupor_0000'
[LUA]  ...K.E.R. - Call of Pripyat\ph_idle:(58):DEBUG: add_to_binder: scheme='ph_idle', section='ph_idle@wait'
[LUA]  ...K.E.R. - Call of Pripyat\ph_idle:(13):_hr: action_idle:reset_scheme: self.object:name()='pri_a16_ph_rupor'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@wait'
[LUA]  ....E.R. - Call of Pripyat\sr_light:(15):Light zone insert
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@base_radio_snd_1'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@free'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@nil'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@free'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@1'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@out'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@1'
[LUA]  ...K.E.R. - Call of Pripyat\sr_idle:(33):DEBUG: add_to_binder: scheme='sr_idle', section='sr_idle@quest'
 
FATAL ERROR
 
[error] Expression    : _valid(bi.mTransform)
[error] Function      : CLBone
[error] File          : /home/biel/code/XRay/OpenXRay/src/Layers/xrRender/SkeletonRigid.cpp
[error] Line          : 211
[error] Description   : anim kils bone matrix
 

stack trace:

xrDebug::GatherInfo(char*, unsigned long, ErrorLocation const&, char const*, char const*, char const*, char const*)
xrDebug::Fail(bool&, ErrorLocation const&, char const*, char const*, char const*, char const*)
/lib/x86_64-linux-gnu/xrRender_GL.so(+0x147d22) [0x7fffeaf63d22]
/lib/x86_64-linux-gnu/xrRender_GL.so(+0x147db8) [0x7fffeaf63db8]
/lib/x86_64-linux-gnu/xrRender_GL.so(+0x147de4) [0x7fffeaf63de4]
/lib/x86_64-linux-gnu/xrRender_GL.so(+0x147de4) [0x7fffeaf63de4]
/lib/x86_64-linux-gnu/xrRender_GL.so(+0x1488b0) [0x7fffeaf648b0]
/lib/x86_64-linux-gnu/xrGame.so(+0x12c265a) [0x7fffe9c5665a]
/lib/x86_64-linux-gnu/xrGame.so(+0x12be756) [0x7fffe9c52756]
/lib/x86_64-linux-gnu/xrGame.so(+0x12db75b) [0x7fffe9c6f75b]
/lib/x86_64-linux-gnu/xrGame.so(+0x12eb2d9) [0x7fffe9c7f2d9]
CObjectList::SingleUpdate(IGameObject*)
CObjectList::Update(bool)
IGame_Level::OnFrame()
/lib/x86_64-linux-gnu/xrGame.so(+0xebb4c8) [0x7fffe984f4c8]
CRenderDevice::FrameMove()
CRenderDevice::ProcessFrame()
/lib/x86_64-linux-gnu/xrEngine.so(+0x43e2b) [0x7ffff7f04e2b]
CRenderDevice::Run()
Startup()

Thread 1 "Primary thread" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff7d093ec in xrDebug::Fail(bool&, ErrorLocation const&, char const*, char const*, char const*, char const*) () from /lib/x86_64-linux-gnu/xrCore.so
(gdb) bt
#0  0x00007ffff7d093ec in xrDebug::Fail(bool&, ErrorLocation const&, char const*, char const*, char const*, char const*) () from /lib/x86_64-linux-gnu/xrCore.so
#1  0x00007fffeaf63d22 in CKinematics::CLBone(CBoneData const*, CBoneInstance&, _matrix<float> const*, unsigned char) () from /lib/x86_64-linux-gnu/xrRender_GL.so
#2  0x00007fffeaf63db8 in CKinematics::Bone_Calculate(CBoneData*, _matrix<float>*) () from /lib/x86_64-linux-gnu/xrRender_GL.so
#3  0x00007fffeaf63de4 in CKinematics::Bone_Calculate(CBoneData*, _matrix<float>*) () from /lib/x86_64-linux-gnu/xrRender_GL.so
#4  0x00007fffeaf63de4 in CKinematics::Bone_Calculate(CBoneData*, _matrix<float>*) () from /lib/x86_64-linux-gnu/xrRender_GL.so
#5  0x00007fffeaf648b0 in CKinematics::CalculateBones(int) () from /lib/x86_64-linux-gnu/xrRender_GL.so
#6  0x00007fffe9c5665a in CWeapon::UpdateXForm() () from /lib/x86_64-linux-gnu/xrGame.so
#7  0x00007fffe9c52756 in CWeapon::UpdateFireDependencies_internal() () from /lib/x86_64-linux-gnu/xrGame.so
#8  0x00007fffe9c6f75b in CWeaponMagazined::UpdateSounds() () from /lib/x86_64-linux-gnu/xrGame.so
#9  0x00007fffe9c7f2d9 in CWeaponPistol::UpdateSounds() () from /lib/x86_64-linux-gnu/xrGame.so
#10 0x00007ffff7f67246 in CObjectList::SingleUpdate(IGameObject*) () from /lib/x86_64-linux-gnu/xrEngine.so
#11 0x00007ffff7f68967 in CObjectList::Update(bool) () from /lib/x86_64-linux-gnu/xrEngine.so
#12 0x00007ffff7f29e61 in IGame_Level::OnFrame() () from /lib/x86_64-linux-gnu/xrEngine.so
#13 0x00007fffe984f4c8 in CLevel::OnFrame() () from /lib/x86_64-linux-gnu/xrGame.so
#14 0x00007ffff7f0365b in CRenderDevice::FrameMove() () from /lib/x86_64-linux-gnu/xrEngine.so
#15 0x00007ffff7f03e57 in CRenderDevice::ProcessFrame() () from /lib/x86_64-linux-gnu/xrEngine.so
#16 0x00007ffff7f04e2b in CRenderDevice::message_loop() [clone .part.0] () from /lib/x86_64-linux-gnu/xrEngine.so
#17 0x00007ffff7f05107 in CRenderDevice::Run() () from /lib/x86_64-linux-gnu/xrEngine.so
#18 0x00007ffff7f39320 in Startup() () from /lib/x86_64-linux-gnu/xrEngine.so
#19 0x00007ffff7f39dfb in RunApplication() () from /lib/x86_64-linux-gnu/xrEngine.so
#20 0x0000555555555885 in entry_point(char const*) ()
#21 0x00005555555555bf in main ()
(gdb) quit
</p>
</details>

maybe those ODE error messages "vector has zero size" influence the CKinematics::CLBone that fails?

I attached the save file that fails for me:
https://ufile.io/y93ltfw1
