### ISSUE TITLE
[COP] - last commit( c5ef6c7 ) --> seems to have broken the finalitzation of tasks

### ISSUE THREAD

**Issue by BielBdeLuna** [Swartz27/xray-16#982]
**Describe the bug**
last commit( c5ef6c7af405c641a004367a8db6fc75f07e9319 ) has broken the finalization of any mission, you can get missions, you can complete parts of the mission but when you actually finish a mission the game crashes, I've tested this in two different missions

**To Reproduce**
finish any mission and the game will crash

**Expected behavior**
don't crash, just finish the mission.

**Screenshots**
not applicable.

**BugTrap error report**

<details>
<summary>Click here to expand/collapse the gdb error messages.</summary>
<p>

(...)

Thread 1 "Primary thread" received signal SIGSEGV, Segmentation fault.
0x00007fffe04c7714 in CGameTaskManager::SetTaskState(CGameTask*, ETaskState, unsigned short) () from /lib/x86_64-linux-gnu/xrGame.so
(gdb) ret
Make selected stack frame return now? (y or n) y
#0  0x00007fffe04c89a7 in CGameTaskManager::UpdateTasks() () from /lib/x86_64-linux-gnu/xrGame.so
(gdb) continue 
Continuing.
 
FATAL ERROR
 
[error] Expression    : <no expression>
[error] Function      : handler_base
[error] File          : /home/biel/code/xray-16/src/xrCore/xrDebug.cpp
[error] Line          : 848
[error] Description   : segmentation fault
 

stack trace:

xrDebug::GatherInfo(char*, unsigned long, ErrorLocation const&, char const*, char const*, char const*, char const*)
xrDebug::Fail(bool&, ErrorLocation const&, char const*, char const*, char const*, char const*)
/lib/x86_64-linux-gnu/xrCore.so(+0x4268b) [0x7ffff7d0868b]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7ffff7718520]
/lib/x86_64-linux-gnu/xrGame.so(+0xdff9a7) [0x7fffe04c89a7]
/lib/x86_64-linux-gnu/xrGame.so(+0xe95858) [0x7fffe055e858]
CRenderDevice::FrameMove()
CRenderDevice::ProcessFrame()
/lib/x86_64-linux-gnu/xrEngine.so(+0x43c4b) [0x7ffff7f03c4b]
CRenderDevice::Run()
Startup()
RunApplication()
/usr/games/xr_3da(+0x1885) [0x555555555885]
/usr/games/xr_3da(+0x15bf) [0x5555555555bf]
/lib/x86_64-linux-gnu/libc.so.6(+0x29fd0) [0x7ffff76fffd0]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x7d) [0x7ffff770007d]
/usr/games/xr_3da(+0x16a5) [0x5555555556a5]

Thread 1 "Primary thread" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff7d0807f in xrDebug::Fail(bool&, ErrorLocation const&, char const*, char const*, char const*, char const*) () from /lib/x86_64-linux-gnu/xrCore.so
(gdb) quit
</p>
</details>

**Desktop (please complete the following information):**
 - OS: [Ubuntu 21.10]
 - OpenXRay build version [c5ef6c7af405c641a004367a8db6fc75f07e9319] with **-DMASTERGOLD=ON**

**Additional context**
none.

**Comment by BielBdeLuna** [comment]
with the latest commits ( 1f3607b2036079a36ba7f9790e1433dc38d3c0b3 ) there is still this error going  on.
here is the complete backtrace:

```
Thread 1 "Primary thread" received signal SIGSEGV, Segmentation fault.
0x00007fffe04c8084 in CGameTaskManager::SetTaskState(CGameTask*, ETaskState, unsigned short) () from /lib/x86_64-linux-gnu/xrGame.so
(gdb) bt
#0  0x00007fffe04c8084 in CGameTaskManager::SetTaskState(CGameTask*, ETaskState, unsigned short) () from /lib/x86_64-linux-gnu/xrGame.so
#1  0x00007fffe04c9307 in CGameTaskManager::UpdateTasks() () from /lib/x86_64-linux-gnu/xrGame.so
#2  0x00007fffe055f118 in CLevel::OnFrame() () from /lib/x86_64-linux-gnu/xrGame.so
#3  0x00007ffff7f029cb in CRenderDevice::FrameMove() () from /lib/x86_64-linux-gnu/xrEngine.so
#4  0x00007ffff7f031c7 in CRenderDevice::ProcessFrame() () from /lib/x86_64-linux-gnu/xrEngine.so
#5  0x00007ffff7f03c4b in CRenderDevice::message_loop() [clone .part.0] () from /lib/x86_64-linux-gnu/xrEngine.so
#6  0x00007ffff7f03f27 in CRenderDevice::Run() () from /lib/x86_64-linux-gnu/xrEngine.so
#7  0x00007ffff7f380b0 in Startup() () from /lib/x86_64-linux-gnu/xrEngine.so
#8  0x00007ffff7f38c2b in RunApplication() () from /lib/x86_64-linux-gnu/xrEngine.so
#9  0x0000555555555885 in entry_point(char const*) ()
#10 0x00005555555555bf in main ()
```

**Comment by BielBdeLuna** [comment]
it's still not solved though! now it fails when getting the task!

```
Thread 1 "Primary thread" received signal SIGSEGV, Segmentation fault.
0x00007fffe04c696c in task_prio_pred(SGameTaskKey const&, SGameTaskKey const&) () from /lib/x86_64-linux-gnu/xrGame.so
(gdb) bt
#0  0x00007fffe04c696c in task_prio_pred(SGameTaskKey const&, SGameTaskKey const&) () from /lib/x86_64-linux-gnu/xrGame.so
#1  0x00007fffe04c9bd9 in void std::__merge_adaptive<__gnu_cxx::__normal_iterator<SGameTaskKey*, std::vector<SGameTaskKey, xalloc<SGameTaskKey> > >, long, SGameTaskKey*, __gnu_cxx::__ops::_Iter_comp_iter<bool (*)(SGameTaskKey const&, SGameTaskKey const&)> >(__gnu_cxx::__normal_iterator<SGameTaskKey*, std::vector<SGameTaskKey, xalloc<SGameTaskKey> > >, __gnu_cxx::__normal_iterator<SGameTaskKey*, std::vector<SGameTaskKey, xalloc<SGameTaskKey> > >, __gnu_cxx::__normal_iterator<SGameTaskKey*, std::vector<SGameTaskKey, xalloc<SGameTaskKey> > >, long, long, SGameTaskKey*, long, __gnu_cxx::__ops::_Iter_comp_iter<bool (*)(SGameTaskKey const&, SGameTaskKey const&)>) () from /lib/x86_64-linux-gnu/xrGame.so
#2  0x00007fffe04c7dc7 in void std::__stable_sort_adaptive<__gnu_cxx::__normal_iterator<SGameTaskKey*, std::vector<SGameTaskKey, xalloc<SGameTaskKey> > >, SGameTaskKey*, long, __gnu_cxx::__ops::_Iter_comp_iter<bool (*)(SGameTaskKey const&, SGameTaskKey const&)> >(__gnu_cxx::__normal_iterator<SGameTaskKey*, std::vector<SGameTaskKey, xalloc<SGameTaskKey> > >, __gnu_cxx::__normal_iterator<SGameTaskKey*, std::vector<SGameTaskKey, xalloc<SGameTaskKey> > >, SGameTaskKey*, long, __gnu_cxx::__ops::_Iter_comp_iter<bool (*)(SGameTaskKey const&, SGameTaskKey const&)>) [clone .constprop.0] () from /lib/x86_64-linux-gnu/xrGame.so
#3  0x00007fffe04c83e5 in CGameTaskManager::GiveGameTaskToActor(CGameTask*, unsigned int, bool, unsigned int) ()
   from /lib/x86_64-linux-gnu/xrGame.so
#4  0x00007fffe07683c0 in luabind::detail::function_object_impl<void (CScriptGameObject::*)(CGameTask*, unsigned int, bool, unsigned int), luabind::meta::type_list<void, CScriptGameObject&, CGameTask*, unsigned int, bool, unsigned int>, luabind::meta::type_list<luabind::converter_policy_injector<2u, luabind::detail::adopt_policy_impl<void> > > >::call(lua_State*, luabind::detail::invoke_context&, int) const ()
   from /lib/x86_64-linux-gnu/xrGame.so
#5  0x00007fffe076b114 in luabind::detail::function_object_impl<void (*)(CScriptGameObject*, CGameTask*, unsigned int, bool), luabind::meta::type_list<void, CScriptGameObject*, CGameTask*, unsigned int, bool>, luabind::meta::type_list<luabind::converter_policy_injector<2u, luabind::detail::adopt_policy_impl<void> > > >::entry_point(lua_State*) () from /lib/x86_64-linux-gnu/xrGame.so
#6  0x00007ffff75627c5 in lj_BC_FUNCC () from /lib/x86_64-linux-gnu/xrLuajit.so
#7  0x00007ffff7515e69 in lua_pcall () from /lib/x86_64-linux-gnu/xrLuajit.so
#8  0x00007ffff75966f1 in luabind::detail::pcall(lua_State*, int, int) () from /lib/x86_64-linux-gnu/xrLuabind.so
#9  0x00007fffe06e4c0d in CScriptBinderObjectWrapper::shedule_Update(unsigned int) () from /lib/x86_64-linux-gnu/xrGame.so
#10 0x00007fffe06d8277 in CScriptBinder::shedule_Update(unsigned int) () from /lib/x86_64-linux-gnu/xrGame.so
#11 0x00007ffff7f67ed8 in CSheduler::ProcessStep() () from /lib/x86_64-linux-gnu/xrEngine.so
#12 0x00007ffff7f68dd1 in CSheduler::Update() () from /lib/x86_64-linux-gnu/xrEngine.so
#13 0x00007fffe0452ee3 in CGamePersistent::OnFrame() () from /lib/x86_64-linux-gnu/xrGame.so
#14 0x00007ffff7f029cb in CRenderDevice::FrameMove() () from /lib/x86_64-linux-gnu/xrEngine.so
#15 0x00007ffff7f031c7 in CRenderDevice::ProcessFrame() () from /lib/x86_64-linux-gnu/xrEngine.so
#16 0x00007ffff7f03c4b in CRenderDevice::message_loop() [clone .part.0] () from /lib/x86_64-linux-gnu/xrEngine.so
#17 0x00007ffff7f03f27 in CRenderDevice::Run() () from /lib/x86_64-linux-gnu/xrEngine.so
#18 0x00007ffff7f380b0 in Startup() () from /lib/x86_64-linux-gnu/xrEngine.so
#19 0x00007ffff7f38c2b in RunApplication() () from /lib/x86_64-linux-gnu/xrEngine.so
#20 0x0000555555555885 in entry_point(char const*) ()
#21 0x00005555555555bf in main ()
(gdb) continue 
Continuing.
 
FATAL ERROR
 
[error] Expression    : <no expression>
[error] Function      : handler_base
[error] File          : /home/biel/code/xray-16/src/xrCore/xrDebug.cpp
[error] Line          : 848
[error] Description   : segmentation fault
 

stack trace:

xrDebug::GatherInfo(char*, unsigned long, ErrorLocation const&, char const*, char const*, char const*, char const*)
xrDebug::Fail(bool&, ErrorLocation const&, char const*, char const*, char const*, char const*)
/lib/x86_64-linux-gnu/xrCore.so(+0x4268b) [0x7ffff7d0868b]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7ffff7718520]
/lib/x86_64-linux-gnu/xrGame.so(+0xdfe96c) [0x7fffe04c696c]
/lib/x86_64-linux-gnu/xrGame.so(+0xe01bd9) [0x7fffe04c9bd9]
/lib/x86_64-linux-gnu/xrGame.so(+0xdffdc7) [0x7fffe04c7dc7]
/lib/x86_64-linux-gnu/xrGame.so(+0xe003e5) [0x7fffe04c83e5]
/lib/x86_64-linux-gnu/xrGame.so(+0x10a03c0) [0x7fffe07683c0]
/lib/x86_64-linux-gnu/xrGame.so(+0x10a3114) [0x7fffe076b114]
/lib/x86_64-linux-gnu/xrLuajit.so(+0x667c5) [0x7ffff75627c5]
/lib/x86_64-linux-gnu/xrLuajit.so(lua_pcall+0xb9) [0x7ffff7515e69]
luabind::detail::pcall(lua_State*, int, int)
/lib/x86_64-linux-gnu/xrGame.so(+0x101cc0d) [0x7fffe06e4c0d]
/lib/x86_64-linux-gnu/xrGame.so(+0x1010277) [0x7fffe06d8277]
CSheduler::ProcessStep()
CSheduler::Update()
/lib/x86_64-linux-gnu/xrGame.so(+0xd8aee3) [0x7fffe0452ee3]
CRenderDevice::FrameMove()
CRenderDevice::ProcessFrame()

Thread 1 "Primary thread" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff7d0807f in xrDebug::Fail(bool&, ErrorLocation const&, char const*, char const*, char const*, char const*) () from /lib/x86_64-linux-gnu/xrCore.so
(gdb) quit
```
